name = "revenueforge"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "revenueforge-db"
database_id = "placeholder-will-be-set-on-deployment"
