name = "revenueforge"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output"

[[d1_databases]]
binding = "DB"
database_name = "revenueforge-db"
database_id = "da0624be-7f9c-4fc7-809a-c79c5641896b"

[[kv_namespaces]]
binding = "KV"
id = "abf6f10d63e4485e94d8f5b8c4408fec"
